### PR TITLE
Update to latest pybind11 for Python 3.11

### PR DESCRIPTION
**Pull request by par5er**
This library fails to compile on Python 3.11 with error `‘PyCodeObject {aka struct PyCodeObject}’ has no member named ‘co_varnames’; did you mean ‘co_names’?`. Caused due to an ancient pybind11 version. Update to main to fix the issue

### CODE REVIEW

**Review by Franteos — COMMENTED** [review]
#190
